### PR TITLE
Change template_path to template_paths

### PR DESCRIPTION
**Pull request by demotu**
Nbconvert 6.0 changed from 'template_path' to 'template_paths' (see https://nbconvert.readthedocs.io/en/latest/changelog.html#significant-changes).
This change in Nbconvert causes errors in jupyter_latex_envs and in jupyter_contrib_nbextensions (see issue 1529 https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1529).

Replacing all instances of 'template_path' with 'template_paths' in both jupyter_latex_envs and in jupyter_contrib_nbextensions fixes the error.

### CODE REVIEW

**Comment by proinsias** [comment]
@jfbercher – can we get this merged?

**Comment by tafia** [comment]
Any news?

**Comment by squeezer44** [comment]
Any progress in here?

**Comment by seralouk** [comment]
Any news? Still getting those warnings...

**Comment by oikosfigueroa** [comment]
Still having the errors when running Jupiter notebook
```[W 22:08:53.245 NotebookApp] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `template_extension, template_file, template_paths`?```
.
.
.
Well, I spent a long time reading at so many posts on Github about this. And I pretty much tried everything. 
--> **I also have Python 3.9, so installing nbconvert<6 was not a possible solution.(Conda tried to find the way but at the end says that installing nbconvert 5.6... etc is not possible because of your 3.9 python version)** 

I started by finding the very first file in the nbconvert just like people suggested, but making the change in only one file doesn't work. And yes, the errors continued appearing, and at the same time I wasn't able to download a notebook as html. 

**My solution: ** I had to find literally every file.py that had template_path and replace it with template_paths.
- Which location for Mac users? In my case and maybe other people: `/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages`
- Go to **Finder>Go>Go to Folder** and enter the path where your site-packages are
- In site-packages I went to **notebook**, **nbconvert** and, **jupyter_contrib_nbextensions**. I looked for the files that had template_path and replace it with template_paths. 

It worked? Yes, it did, but this is very annoying. Why? Well, when you run Conda update --all, apparently it solves all your problems, but not this one. Unless you do manual changes, nothing is gonna work. Kind of frustrating, I agree. 

I hope the people in charge of approving or making changes work on this soon and I would love to see the improvements. 

Hope someone finds this a little helpful. 🌻 

Kalfilor

**Comment by Betristor** [comment]
Any news? Still not working...

**Comment by anders830** [comment]
I got the same issues, is there any progress?

**Comment by jfbercher** [comment]
Thank you for this pull request that I just merged. I hope it will be suitable and helpful!

As you can see, unfortunately, I don't have the time to continue the development of this extension, which I still use very often. 
Are there any volunteers to maintain it or continue the development? A big project would be to port it to jupyter-lab.

**Comment by moltra** [comment]
> Thank you for this pull request that I just merged. I hope it will be suitable and helpful!
> 
> As you can see, unfortunately, I don't have the time to continue the development of this extension, which I still use very often. Are there any volunteers to maintain it or continue the development? A big project would be to port it to jupyter-lab.

I will help maintain it if you still need the help.  I do not have a lot of experience, I learn fast.

**Pull request merged**
